#!/usr/bin/env python

from gprot.summary import summarize_fits

if __name__=='__main__':
    import argparse

    parser = argparse.ArgumentParser()

    parser.add_argument('resultsdir')
    parser.add_argument('--quantiles', nargs='+', default=[0.05,0.16,0.5,0.84,0.95])
    parser.add_argument('--aigrain', action='store_true')

    args = parser.parse_args()

    df = summarize_fits(args.resultsdir, quantiles=args.quantiles, truths=args.aigrain)
    results_file = '{}_summary.h5'.format(resultsdir)
    df.to_hdf(results_file, 'df')
    print('Summarized results for {} fits written to {}.'.format(len(df), results_file))
    

